# This is a basic workflow to help you get started with Actions

name: CI to Docker Hub

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      spark_version:
        default: '3.0.1'
        description: 'Spark Version'
      hadoop_version:
        default: '2.7'
        description: 'Hadoop Version'
      scala_version:
        default: '2.11.12'
        description: 'Scala version'
      sbt_version:
        default: '1.3.12'
        description: 'SBT version'        
      image_tag:
        default: 'tvdgnr/spark-standalone:latest'
        description: 'Docker image tag'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          build-args: |
            spark_version=${{ github.event.inputs.spark_version }}
            hadoop_version=${{ github.event.inputs.hadoop_version }}
            scala_version=${{ github.event.inputs.scala_version }}
            sbt_version=${{ github.event.inputs.sbt_version }}
          tags: ${{ github.event.inputs.image_tag }}
